AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/LineLength:
  Max: 100

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '*.gemspec'
    - 'spec/**/*.rb'

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled:  true

Style/HashTransformValues:
  Enabled: true
